project:
  type: website
  output-dir: docs


website:
  title: "DS 연예진"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - hw1
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



