project:
  type: website
  output-dir: docs


website:
  title: "DS 연예진"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: hw1.qmd
        text: hw1
      - href: hw2.qmd
        text: hw2
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



