project:
  type: website
  output-dir: docs


website:
  title: "LS빅데이터 조별과제"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: blog.qmd
        text: blog
      - href: mpg.qmd
        text: mpg
      - href: finala-group.qmd
        text: a-project
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



