project:
  type: website
  output-dir: docs


website:
  title: "연예진"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: blog.qmd
        text: blog
      - href: mpg.qmd
        text: mpg
      - href: finala-group.qmd
        text: a-project
   
format:
  html:
    theme: cosmo
    toc: true


