---
title: "hw8"
author: "연예진"
data: "2024 -09-02"
categories: [bigdata]
jupyter: python3
---

# ADP 표본점수
2022년에 실시 된 ADP 실기 시험의 통계파트 표준점수는 평균이 30, 표준편차가 5인 정규분포를 따른다고 한다.
1) ADP 실기 시험의 통계파트 표준점수의 밀도함수를 그려보세요.
```{python}
import numpy as np
from scipy.stats import norm
import matplotlib.pyplot as plt

x = np.linspace(15, 45, 500)
y = norm.pdf(x, loc=30, scale=5)
plt.plot(x, y) 
```

2) ADP 수험생을 임의로 1명을 선택하여 통계 점수를 조회했을때 45점 보다 높은 점수를 받았을 확률을 구하세요.
```{python}
1 - norm.cdf(45, 30, 5)
```

0.001349

3) 슬통이는 상위 10%에 해당하는 점수를 얻었다고 한다면, 슬통이의 점수는 얼마인지 계산해보세요.
```{python}
norm.ppf(0.9, 30, 5)
```

36.407

4) 슬기로운 통계생활의 해당 회차 수강생은 16명이었다고 한다. 16명의 통계 파트 점수를 평균내었을 때, 이 평균값이 따르는 분포의 확률밀도 함수를 1번의 그래프와 겹쳐 그려보세요.
```{python}
x = np.linspace(15, 45, 500)
y = norm.pdf(x, loc=30, scale=5)
plt.plot(x, y) 

y2 = norm.pdf(x, loc=30, scale=5/np.sqrt(16))
plt.plot(x, y2, color="red")

```

5) 슬기로운 통계생활 ADP 반 수강생들의 통계점수를 평균내었다고 할 때, 이 값이 38점보다 높게 나올 확률을 구하세요.
```{python}
1-norm.cdf(38, loc=30, scale=5/np.sqrt(16))

```

7.76885222819601e-11

# Covid 19 발병률
Covid‑19의 발병률은 1%라고 한다. 다음은 이번 코로나 사태로 인하여 코로나 의심 환자들 1,085명을 대상으로 슬통 회사의 “다잡아” 키트를 사용하여 양성 반응을 체크한 결과이다.
키트 \ 실제 양성 음성
양성 370 10
음성 15 690

1) 다잡아 키트가 코로나 바이러스에 걸린 사람을 양성으로 잡아낼 확률을 계산하세요.
```{python}

370/385

```

2) 슬통 회사에서 다잡아 키트를 사용해 양성으로 나온 사람이 실제로는 코로나 바이러스에 걸려있을 확률을 97%라며, 키트의 우수성을 주장했다. 이 주장이 옳지 않은 이유를 서술하세요.

표본으로 뽑힌 집단의 확률과 슬통회사에서 주장한 확률이 다르다.

3) Covid‑19 발병률을 사용하여,키트의 결과값이 양성으로 나온 사람이 실제로 코로나 바이러스에 걸려있을 확률을 구하세요.
```{python}
(0.01* (370/385)) / (0.01 * (370/385) + 0.99 * (10 / 700))

```

0.40459


# 카이제곱분포와 표본분산
자유도가 𝑘인 카이제곱분포를 따르는 확률변수 𝑋 를 𝑋 ∼ (𝜒^2)*(𝑘)과 같이 나타내고, 이 확률변수의 확률밀도함수는 다음과 같습니다.



다음의 물음에 답하세요.
1) 자유도가 4인 카이제곱분포의 확률밀도함수를 그려보세요.
```{python}

from scipy.stats import chi2
import matplotlib.pyplot as plt
import numpy as np
k=np.linspace(-2, 40, 500)
y=chi2.pdf(k, df=4)
plt.plot(k, y, color= "black")

```


2) 다음의 확률을 구해보세요.
𝑃 (3 ≤ 𝑋 ≤ 5)
```{python}
chi2.cdf(5, 4) - chi2.cdf(3, 4)

```



3) 자유도가 4인 카이제곱분포에서 크기가 1000인 표본을 뽑은 후, 히스토그램을 그려보세요.
```{python}

import numpy as np
np.random.seed(2024)
#chi2.rvs(df, loc=0, scale=1, size=1, random_state=None)
x = chi2.rvs(4, loc=0, scale=1, size=1000)
plt.hist(x, color = "black",histtype='bar')
plt.figure()

```

4) 자유도가 4인 카이제곱분포를 따르는 확률변수에서 나올 수 있는 값 중 상위 5%에 해당하는 값은 얼마인지 계산해보세요.
```{python}
import scipy.stats as stats
data =stats.chi2(4, loc=0, scale=1)
data.ppf(0.95) 


```

data.ppf(0.95) = 9.487

5) 3번에서 뽑힌 표본값들 중 상위 5%에 위치한 표본의 값은 얼마인가요?
```{python}
np.percentile(x, 95)

```

10.006

6) 평균이 3, 표준편차가 2인 정규분포를 따르는 확률변수에서 크기가 20인 표본, 𝑥1, ..., 𝑥20,을 뽑은 후 표본분산을 계산한 것을 𝑠1^2이라 생각해보죠. 다음을 수행해보세요!
```{python}
from scipy.stats import norm

np.random.seed(2024)
x = norm.rvs(3, 2, size=20)


```

• 같은 방법으로 500개의 𝑠^2 들, 𝑠(1)^2, 𝑠(2)^2, ..., 𝑠(500)^2 발생시킵니다.
```{python}
samples=[]

for i in range(500):
    x = norm.rvs(3, 2, size=20)
    samples.append(np.var(x, ddof=1))


```

• 발생한 500개의 𝑠^2 들 각각에 4.75를 곱하고, 그것들의 히스토그램을 그려보세요. (히스토그램을 그릴 때 probability = TRUE 옵션을 사용해서 그릴 것)
```{python}
new_samples = np.array(samples) * 4.75
plt.hist(new_samples, density = True, color="black")
plt.figure()

```

• 위에서 그린 히스토그램에 자유도가 19인 카이제곱분포 확률밀도함수를 겹쳐그려보세요.

```{python}
new_samples = np.array(samples) * 4.75
plt.hist(new_samples, density = True, color="black")
k=np.linspace(-2, 40, 500)
y=chi2.pdf(k, df=19)
plt.plot(k, y, color= "red")

```